version: '3'

networks:
  default:
    driver: bridge

volumes:
  db-volume:

services:
  db:
    image: yzh44yzh/wg_forge_backend_env:1.1
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - db-volume:/var/lib/wg/data
